### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by blamot** [aeberhardo/phantomjs-linux-armv6l#3] opened 2013-08-02 06:55 UTC
This one is to be closed. Sorry, my mistake.
It gives an parse error, when not reading the Phantom manual to start with.... 

It works great actually, installed it on my RPI and runs without errors.

**Comment by aeberhardo** [comment] 2013-08-02 08:34
Duplicate of #4, #5, #6, #7.

Also no information is given as to when this "Parse Error" occurs.
- What operation are you executing that yields the error?
- Does the error also occur when using the latest official version from http://phantomjs.org/ ?

**Comment by aeberhardo** [comment] 2013-08-22 07:02
Closed due to lack of details given.

**Closed as completed by aeberhardo** 2013-08-22 07:02 UTC
